### ISSUE TITLE
Design pattern implementations in TypeScript Update Request

### ISSUE THREAD

**Issue by MaherJendoubi** [torokmark/contact-me#1]
Hi Torok,

Please update Design pattern implementations in TypeScript to version 2.0 RC.
https://blogs.msdn.microsoft.com/typescript/2016/08/30/announcing-typescript-2-0-rc/

Thank you,
Best,
Maher

**Comment by torokmark** [comment]
Hi Maher,

Please, take a look at it now.

Best regards,
Mark

**Comment by MaherJendoubi** [comment]
👍 👍 👍
